apiVersion: apps/v1
kind: Deployment
metadata:
  name: tender-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tender-system
  template:
    metadata:
      labels:
        app: tender-system
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: app-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: app-files
        hostPath:
          path: /home/leonard/Desktop/temp-app/build
          type: Directory